---
title: "Weightlift Exercise Prediction"
author: "Long You Cai"
date: '2014-12-21'
output:
  html_document:
    theme: spacelab
---

###Abstract

Wearable technology is becoming one of the hottest new technologies, with many fitness and activity trackers being developed at a rapid pace. This influx of raw data requires new processing methods to transform it into useful information. In this work, we present a method for classifying wearable accelerometer data into corresponding weightlifting exercise types.

###Dataset

We use a modified version of the Weight Lifting Exercises Dataset[^1] collected by the [Groupware\@LES team][groupware].

The original dataset consists of `39 242` observations of `159` variables. Our [Practical Machine Learning][pml] version consists of a training subset with `19 622` of the observations alongside a test set of `20` other cases with their classifications removed.

###Method

All data processing was done in [R][rlang], with preliminary data checking in a spreadsheet program.

We first pre-process the data, removing all incomplete columns as well as various factors which should not affect the prediction such as the test number, subject username and timestamps. This leaves `54` usable predictors to build our model with.

For the model itself, we used random forest classification, using the [Caret][caretlib] and [randomForest][rflib] libraries in R. We ran it with an initial seed of `1` and the default `500` random trees generated.

Due to the nature of the random forest model itself, no cross validation was needed[^2].

###Results

Our model predicted the training data very well, with an estimated Out Of Bag error of `0.15%`. This corresponds with an estimated Out of Sample accuracy of `99.85%`. Such a high value can be explained through overfitting as while random forest classification does not need explicit cross validating, it is still prone to overfitting. The real world Out of Sample accuracy can be expected to be markedly lower.

Below is the confusion matrix and class errors for each weightlifting exercise type.

```{r, echo=FALSE}
load('learnedRfModel.R')
pml.rf$confusion
```

###Conclusion

The random forest classification method is an effective way to process the large amounts of data generated by the newest personal fitness and activity trackers.

[^1]: Velloso, E.; Bulling, A.; Gellersen, H.; Ugulino, W.; Fuks, H. Qualitative Activity Recognition of Weight Lifting Exercises. Proceedings of 4th International Conference in Cooperation with SIGCHI (Augmented Human '13). Stuttgart, Germany: ACM SIGCHI, 2013.

[^2]: Breiman, Leo, and Adele Cutler. "Random Forests." Random Forests - Classification Description. Department of Statistics, University of California, Berkeley. Web. 21 Dec. 2014.

[groupware]: http://groupware.les.inf.puc-rio.br/har#weight_lifting_exercises
[pml]: https://www.coursera.org/course/predmachlearn
[rlang]: http://www.r-project.org/
[caretlib]: http://topepo.github.io/caret/index.html
[rflib]: http://cran.r-project.org/web/packages/randomForest/index.html